RUN \
    --mount=type=bind,from=ghcr.io/ublue-os/akmods-nvidia:fsync-40,src=/rpms,dst=/tmp/akmods-rpms,rw \
    find /tmp/akmods-rpms \
    && curl -Lo /tmp/nvidia-install.sh https://raw.githubusercontent.com/ublue-os/hwe/main/nvidia-install.sh \
    && sed -i '/^echo "options nvidia NVreg_TemporaryFilePath=\/var\/tmp"/d; /^cp \/etc\/modprobe.d\/nvidia-modeset.conf \/usr\/lib\/modprobe.d\/nvidia-modeset.conf/d' /tmp/nvidia-install.sh \
    && chmod +x /tmp/nvidia-install.sh \
    && IMAGE_NAME=base-main FEDORA_MAJOR_VERSION="$(rpm -E %fedora)" /tmp/nvidia-install.sh \
    && rm -f /usr/share/vulkan/icd.d/nouveau_icd.*.json \
    && ln -s libnvidia-ml.so.1 /usr/lib64/libnvidia-ml.so \
    && ostree container commit
